CREATE TABLE realms (
  id        SERIAL PRIMARY KEY,
  region    CHARACTER VARYING,
  name      CHARACTER VARYING,
  slug      CHARACTER VARYING UNIQUE,
  updating  CHARACTER VARYING,
  createdAt TIMESTAMP
);
